#!/bin/bash

docker build -f runner/Dockerfile . -t buildkite-cuda-runner
docker run -v `pwd`/test_numba.py:/test_numba.py:ro -it --runtime=nvidia buildkite-cuda-runner nvidia-smi
docker run -v `pwd`/test_numba.py:/test_numba.py:ro -it --runtime=nvidia buildkite-cuda-runner pytest test_numba.py
