steps:
  - label: ':hammer: Build Runner Image'
    command: docker build -f .buildkite/runner/Dockerfile . -t buildkite-cuda-runner:${BUILDKITE_JOB_ID} -t buildkite-cuda-runner:${BUILDKITE_COMMIT}
  - label: ':shrug: Test'
    command:
      - echo "--- nvidia-smi"
      - nvidia-smi
      - echo "--- pytest"
      - pytest test_numba.py
    plugins:
      uw-ipd/docker:
        runtime: "nvidia"
        image: "buildkite-cuda-runner:${BUILDKITE_JOB_ID}"
